# Workflow for publishing javascirpt api package
name: publish

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  actions: read
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bindings/javascript
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: bindings/javascript/pnpm-lock.yaml
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build javascript api package
        run: pnpm build

      - name: Publish packages to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
